apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer   # <-- Must be LoadBalancer, not NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000